# Generated by Django 5.2.15 on 2026-06-23 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("height", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("winter", models.CharField(blank=True, max_length=10)),
                ("summer", models.CharField(blank=True, max_length=10)),
                ("autumn", models.CharField(blank=True, max_length=10)),
                ("spring", models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("fam", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=150)),
                ("otc", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="PerevalAdded",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beauty_title", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("other_titles", models.CharField(blank=True, max_length=255)),
                ("connect", models.TextField(blank=True)),
                ("add_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "coords",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="pereval.coords"
                    ),
                ),
                (
                    "level",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="pereval.level"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perevals",
                        to="pereval.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.TextField()),
                ("title", models.CharField(max_length=255)),
                (
                    "pereval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="pereval.perevaladded",
                    ),
                ),
            ],
        ),
    ]
